controllers/CompanyController.php
<?php

namespace app\controllers;

use app\helpers\FilesHelper;
use app\models\CompanyCategory;
use app\models\CompanyCompanyCategory;
use Yii;
use app\models\Company;
use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use dosamigos\transliterator\TransliteratorHelper;
use yii\sphinx\Query;
use yii\widgets\ListView;

/**
 * CompanyController implements the CRUD actions for Company model.
 */
class CompanyController extends CController
{
    public $layout = 'lk';

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Company models.
     * @param integer $user_id
     * @return mixed
     */
    public function actionIndex($user_id)
    {
        if ($user_id == Yii::$app->user->id) {
            $dataProvider = new ActiveDataProvider([
                'query' => Company::find()->where(['c_user_id' => Yii::$app->user->id])->orderBy('id DESC'),
            ]);

            $dataProvider->pagination = [
                'defaultPageSize' => 100,
                'pageSizeLimit' => [100, 100],
            ];

            return $this->render('index', [
                'dataProvider' => $dataProvider,
            ]);
        } else {
            $company = Company::find();
            return $this->render('index', [
                'model' => $company,
            ]);
        }
    }

    public function actionList($category, $subcategory = '')
    {
        $this->layout = 'inner';

        if (isset($category) && $subcategory == '') {
            $category_id = CompanyCategory::findOne(['alias' => $category])->id;
            $dataProvider = new ActiveDataProvider([
                'query' => Company::find()
                    ->join('join', 'company_company_category', 'company_company_category.company_id = company.id')
                    ->join('join', 'company_category', 'company_category.id = company_company_category.category_id')
                    ->where(['checked' => true])
                    ->andWhere(['company_category.id' => $category_id])
                    ->orderBy('id DESC'),
            ]);
        } else if (isset($subcategory) && $subcategory != '') {
            $subcategory_id = CompanyCategory::findOne(['alias' => $subcategory])->id;
            $dataProvider = new ActiveDataProvider([
                'query' => Company::find()
                    ->join('join', 'company_company_category', 'company_company_category.company_id = company.id')
                    ->join('join', 'company_category', 'company_category.id = company_company_category.subcategory_id')
                    ->where(['checked' => true])
                    ->andWhere(['company_category.id' => $subcategory_id])
                    ->orderBy('id DESC'),
            ]);
        } else {
            $dataProvider = new ActiveDataProvider([
                'query' => Company::find()->where(['checked' => true])->orderBy('id DESC'),
            ]);
        }

        $dataProvider->pagination = [
            'defaultPageSize' => 4,
            'pageSizeLimit' => [4, 100],
        ];

        return $this->render('list', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionSearch()
    {
        $this->layout = 'inner';

        $q = (!empty(Yii::$app->request->get()['q'])) ? Yii::$app->request->get()['q'] : ' ';

        $query = new Query;
        $query = $query->from('company')->match($q);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $dataProvider->pagination = [
            'defaultPageSize' => 4,
            'pageSizeLimit' => [4, 100],
        ];

        return $this->render('search', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Company model.
     * @param string $alias
     * @return mixed
     */
    public function actionView($alias)
    {
        $this->layout = 'inner';
        $model = Company::findOne(['alias' => $alias]);

        if ($model->checked) {
            return $this->render('view', [
                'model' => $model,
            ]);
        } else {
            echo 123; exit;
        }
    }

    /**
     * Creates a new Company model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @param integer $user_id
     * @return mixed
     */
    public function actionCreate($user_id)
    {
        $company = new Company();

        if (isset(Yii::$app->request->post()['Company'])) {
            $company->load(Yii::$app->request->post());
            $company->alias = mb_strtolower(str_replace(' ', '-',
                TransliteratorHelper::process($company->name, '', 'en')), 'utf8');
            $company->c_user_id = Yii::$app->user->id;
            $company->site_url = str_replace('http://', '', Yii::$app->request->post()['Company']['site_url']);

            if ($company->save()) {
                exec('sh /home/iqdev/reindex_sphinx.sh');
                return $this->redirect(['/company/index', 'user_id' => $user_id, '#' => 'content']);
            }
        } else {
            //удалить папку, созданную при добавлении компании, если компанию чувак так и не добавил и ушел со страницы
            $new_company_id = Company::find()->orderBy('id DESC')->one()->id + 1;
            if (is_dir(Yii::getAlias('@webroot') . '/upload/company/'.$new_company_id)) {
                FilesHelper::removeDirectory(Yii::getAlias('@webroot') . '/upload/company/'.$new_company_id);
            }
        }

        return $this->render('lk/create', [
            'model' => $company,
        ]);
    }

    public function actionEdit($id, $user_id)
    {
        $company = $this->findModel($id);

        if (isset(Yii::$app->request->post()['Company'])) {
            $company->vk = '';
            $company->fb = '';
            $company->inst = '';
            $company->ok = '';
            $company->mail = '';
            $company->load(Yii::$app->request->post());
            $company->c_user_id = Yii::$app->user->id;
            $company->site_url = str_replace('http://', '', Yii::$app->request->post()['Company']['site_url']);
            $company->site_url = str_replace('https://', '', Yii::$app->request->post()['Company']['site_url']);
            $company->site_url = str_replace('/', '', Yii::$app->request->post()['Company']['site_url']);

            if ($company->save()) {
                return $this->redirect(['/company/index', 'user_id' => $user_id, '#' => 'content']);
            } else {
                return $this->render('lk/edit', [
                    'model' => $company,
                ]);
            }
        }

        return $this->render('lk/edit', [
            'model' => $company,
        ]);
    }

    /**
     * Updates an existing Company model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @param integer $user_id
     * @return mixed
     */
    public function actionUpdate($id, $user_id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Company model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        FilesHelper::removeDirectory(Yii::getAlias('@webroot') . '/upload/company/'.$id);

        return $this->redirect(['index']);
    }

    public function actionDeleterubric()
    {
        echo CompanyCompanyCategory::findOne(Yii::$app->request->post()['id'])->delete(); exit;
    }

    public function actionRemoveimage($id)
    {
        unlink(Yii::getAlias('@webroot') . '/upload/company/'.$id.'/gallery/'.Yii::$app->request->post()['image_id'].'.png');
        unlink(Yii::getAlias('@webroot') . '/upload/company/'.$id.'/gallery/66/'.Yii::$app->request->post()['image_id'].'.png');
        unlink(Yii::getAlias('@webroot') . '/upload/company/'.$id.'/gallery/80/'.Yii::$app->request->post()['image_id'].'.png');
    }

    public function actionUpload($id, $type)
    {
        $model = new Company();

        if ($type == 'g') {
            $model->gallery_image = UploadedFile::getInstance($model, 'gallery_image');
            if ($model->validate(['gallery_image'])) {
                if (!is_dir(Yii::getAlias('@webroot') . '/upload/company/'.$id)) {
                    mkdir(Yii::getAlias('@webroot') . '/upload/company/'.$id);
                }
                if (!is_dir(Yii::getAlias('@webroot') . '/upload/company/'.$id.'/gallery')) {
                    mkdir(Yii::getAlias('@webroot') . '/upload/company/'.$id.'/gallery');
                }
                if (!is_dir(Yii::getAlias('@webroot') . '/upload/company/'.$id.'/gallery/66')) {
                    mkdir(Yii::getAlias('@webroot') . '/upload/company/'.$id.'/gallery/66');
                }
                if (!is_dir(Yii::getAlias('@webroot') . '/upload/company/'.$id.'/gallery/80')) {
                    mkdir(Yii::getAlias('@webroot') . '/upload/company/'.$id.'/gallery/80');
                }
                $last_image_name = scandir(Yii::getAlias('@webroot') . '/upload/company/'.$id.'/gallery/66');
                natsort($last_image_name);

                if (count($last_image_name) > 2) {
                    $last_image_name = explode('.', end($last_image_name));

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\User;
use Yii;
use yii\base\Security;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use yii\web\Response;
use yii\widgets\ActiveForm;
use yii\data\ActiveDataProvider;
use app\models\CompanyCategory;
use dosamigos\transliterator\TransliteratorHelper;

class SiteController extends CController
{
    public $layout = 'main';

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionSignup()
    {
        $login_form = new LoginForm();
        $security = new Security();
        $model = new User();
        $model->attributes = Yii::$app->request->post()['User'];
        $model->salt = $security->generateRandomString(12);
        $model->repassword = crypt($model->password, $model->salt);
        $model->password = crypt($model->password, $model->salt);
        $model->c_date = date('Y-m-d H:i:s');

        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }

        if ($model->save()) {
            if ($login_form->load(['LoginForm' => [
                    'email' => $model->email,
                    'password' => Yii::$app->request->post()['User']['password']
                ]]) && $login_form->login()) {
                Yii::$app->response->cookies->add(new \yii\web\Cookie([
                    'name' => 'welcome',
                    'value' => '1'
                ]));
                $this->redirect(['/user/edit', 'user_id' => Yii::$app->user->id, 'welcome' => 'true']);
            } else {
                $this->redirect('/');
            }
        }
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();

        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }

        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            $this->redirect(['/user/edit', 'user_id' => Yii::$app->user->id]);
        } else {
            return $this->render('index', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionSpravochnik()
    {
        $this->layout = 'inner';

        return $this->render('spravochnik');
    }

    public function actionTest()
    {
        exec('sh /home/iqdev/reindex_sphinx.sh', $output);
        print_r($output);
    }
}

views/layouts/inner.php
<?php
use yii\helpers\Html;
use app\assets\AppAsset;
use yii\bootstrap\ActiveForm;
use yii\widgets\Spaceless;
use app\models\CompanyCategory;
use yii\helpers\Url;

/* @var $this \yii\web\View */
/* @var $content string */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

AppAsset::register($this);
$model = new \app\models\User();
$login_form = new \app\models\LoginForm();
$categories = CompanyCategory::find()->where(['parent_id' => 0])->orderBy('name ASC')->all();
$q = (!empty(Yii::$app->request->get()['q'])) ? Yii::$app->request->get()['q'] : '';
?>
<?php Spaceless::begin(); ?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="initial-scale=1.0, minimum-scale=1.0">

    <?= Html::csrfMetaTags() ?>
    <title>Главная / <?= Html::encode(Yii::$app->name) ?></title>
    <?php $this->head() ?>
</head>
<body class="<?=(Yii::$app->request->cookies->getValue('welcome')) ? 'modaled' : ''?>">
<?php $this->beginBody() ?>
<div id="sign" class="modal <?=(Yii::$app->request->cookies->getValue('welcome')) ? 'active' : ''?>">
    <div class="modal-dialog">
        <div class="modal-close"></div>
        <?php if (Yii::$app->request->cookies->getValue('welcome')): ?>
            <h3>Уважаемый <?=\app\models\User::findOne(Yii::$app->user->id)->name?>,</h3><br />
            <p>Спасибо за регистрацию на портале PosadObzor!</p><br />
            <p>Регистрируясь на нашем портале</p>
            <p>Вы получаете возможность создавать объявления,</p>
            <p>добавлять свои компании в справочник, комментировать компании,</p>
            <p>а так же другие расширенные возможности.<p><br />
            <p>С уважением, Администрация портала PosadObzor</p>
        <?php else: ?>
            <div class="signup">
                <div class="signup-title">Регистрация / Авторизация</div>
                <div class="signup-block">
                    <div class="signup-block-tabs">
                        <a class="signup-block-tabs-tab active" href="#/signup/reg">Регистрация</a>
                        <a class="signup-block-tabs-tab" href="#/signup/login">Войти</a>
                    </div>
                    <div class="signup-block-content">
                        <div class="signup-block-content-item active">
                            <?php $form = ActiveForm::begin([
                                'id' => 'reg-form',
                                'method' => 'post',
                                'action' => \yii\helpers\Url::toRoute('/site/signup'),
                                'options' => ['class' => 'form-horizontal'],
                                'enableAjaxValidation' => true,
                                'fieldConfig' => [
                                    'template' => "
                                    <div class=\"signup-block-content-item-field\">{label}<span class=\"star\">*</span>\n
                                        {input}<div class=\"signup-block-content-item-field__error\">{error}</div></div>",
                                ],
                            ]); ?>

                            <?= $form->field($model, 'name') ?>
                            <?= $form->field($model, 'email')->textInput(['class' => 'email-mask']) ?>
                            <?= $form->field($model, 'password')->passwordInput() ?>
                            <?= $form->field($model, 'repassword')->passwordInput() ?>
                            <div class="signup-block-content-item-submit">
                                <input id="submit_reg" type="submit" value="Зарегистрироваться" />
                                <label for="submit_reg"></label>
                            </div>
                            <div class="signup-block-content-item__info">
                                Поля отмеченные <span class="star">*</span> обязательны для заполнения
                            </div>
                            <?php ActiveForm::end(); ?>
                        </div>
                        <div class="signup-block-content-item">

                            <?php $form = ActiveForm::begin([
                                'id' => 'login-form',
                                'method' => 'post',
                                'action' => \yii\helpers\Url::toRoute('/site/login'),
                                'options' => ['class' => 'form-horizontal'],
                                'enableAjaxValidation' => true,
                                'fieldConfig' => [
                                    'template' => "
                                    <div class=\"signup-block-content-item-field\">{label}<span class=\"star\">*</span>\n
                                        {input}<div class=\"signup-block-content-item-field__error\">{error}</div></div>",
                                ],
                            ]); ?>

                            <?= $form->field($login_form, 'email')->textInput(['class' => 'email-mask']) ?>
                            <?= $form->field($login_form, 'password')->passwordInput() ?>
                            <!--                            <div class="signup-block-content-item-checkbox">-->
                            <!--                                <input type="checkbox" name="LoginForm[rememberMe]" class="checkbox" id="remember_me" />-->
                            <!--                                <label for="remember_me">Запомнить меня</label>-->
                            <!--                            </div>-->
                            <div class="signup-block-content-item-submit">
                                <input id="submit_login" type="submit" value="Войти" />
                                <label for="submit_login"></label>
                            </div>
                            <div class="signup-block-content-item-oauth">
                                <div class="signup-block-content-item-oauth-text">ВОЙТИ ЧЕРЕЗ</div>
                                <div class="signup-block-content-item-oauth-icons">
                                    <a href="" class="signup-block-content-item-oauth-icons-icon vk"></a>
                                    <a href="" class="signup-block-content-item-oauth-icons-icon fb"></a>
                                    <a href="" class="signup-block-content-item-oauth-icons-icon tw"></a>
                                    <a href="" class="signup-block-content-item-oauth-icons-icon mail"></a>
                                </div>
                            </div>
                            <?php ActiveForm::end(); ?>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
<header class="short">
    <div class="header-parallax__shadow"></div>
    <div class="header-content">
        <div class="header-content-signup">
            <?php if (isset(\Yii::$app->user->identity)): ?>
                <a class="header-content-signup-login" href="<?= \yii\helpers\Url::toRoute(['/user/edit', 'user_id' => \Yii::$app->user->id]) ?>">
                    <div class="header-content-signup-login text"><?= \Yii::$app->user->identity->name ?></div>
                    <div class="header-content-signup-login icon"></div>
                </a>
                <a class="header-content-signup-reg" data-method="post" href="<?= \yii\helpers\Url::toRoute('/site/logout') ?>">
                    <div class="header-content-signup-reg text">Выход</div>
                </a>
            <?php else: ?>
                <a class="header-content-signup-login open-modal" data-modal-id="sign" href="#/signup/login">
                    <div class="header-content-signup-login text">ВХОД</div>
                    <div class="header-content-signup-login icon"></div>
                </a>
                <a class="header-content-signup-reg open-modal" data-modal-id="sign" href="#/signup/reg">
                    <div class="header-content-signup-reg text">РЕГИСТРАЦИЯ</div>
                    <div class="header-content-signup-reg icon"></div>
                </a>
            <?php endif; ?>
        </div>
        <div class="header-content-title">
            <a href="/">
                <div class="header-content-title__white">СПРАВОЧНО-ИНФОРМАЦИОННЫЙ РЕСУРС </div>
                <div class="header-content-title__black">POSAD OBZOR</div>
            </a>
        </div>
        <div class="header-content-search">
            <form action="<?=Url::toRoute(['/company/search'])?>" method="get">
                <div class="header-content-search-input">
                    <input class="header-content-search-input-text" type="text" name="q"
                           value="<?=$q?>" placeholder="Я хочу найти интересный ресторан..." />
                    <div class="header-content-search-input-submit">
                        <input class="header-content-search-input-submit__button" type="submit"
                               id="header-content-search-input-submit__button" value="ИСКАТЬ" />
                        <label for="header-content-search-input-submit__button"></label>
                    </div>
                </div>
                <div class="header-content-search-checkbox">
                    <input type="checkbox" name="checkbox_service" class="checkbox" id="checkbox_service" />
                    <label for="checkbox_service">Поиск по услугам</label>

                    <input type="checkbox" name="checkbox_goods" class="checkbox" id="checkbox_goods" />
                    <label for="checkbox_goods">Поиск по товарам</label>
                </div>
            </form>
        </div>
        <div class="header-content-toggles">
            <a class="header-content-toggles-toggle menu" href="<?=Url::toRoute(['/site/spravochnik'])?>">
                <div class="header-content-toggles-toggle-text">СПРАВОЧНИК</div>
            </a>
            <a class="header-content-toggles-toggle" href="">
                <div class="header-content-toggles-toggle-text">ГДЕ ПЕРЕКУСИТЬ</div>
            </a>
            <a class="header-content-toggles-toggle" href="">
                <div class="header-content-toggles-toggle-text">ОБРАЗОВАНИЕ</div>
            </a>
            <a class="header-content-toggles-toggle" href="">
                <div class="header-content-toggles-toggle-text">ГДЕ ПЕРЕНОЧЕВАТЬ</div>
            </a>
            <a class="header-content-toggles-toggle" href="">
                <div class="header-content-toggles-toggle-text">МЕДИЦИНА</div>
            </a>
            <a class="header-content-toggles-toggle" href="">
                <div class="header-content-toggles-toggle-text">АВТОМОБИЛИ</div>
            </a>
            <a class="header-content-toggles-toggle" href="">
                <div class="header-content-toggles-toggle-text">НОЧНАЯ ЖИЗНЬ</div>
            </a>
        </div>
    </div>
    <div class="header-under_menu">
        <div class="header-under_menu-triangle"></div>
        <div class="header-under_menu-back">
            <div class="header-under_menu-panel">
                <div class="header-under_menu-wrapper" id="scrollbar">
                    <div class="header-under_menu-content">
                        <?php foreach ($categories as $category): ?>
                            <div class="header-under_menu-content-item">
                                <a href="<?=Url::toRoute([
                                    '/company/list',
                                    'category' => $category->alias
                                ])?>"><?=mb_strtoupper($category->name, 'utf8')?></a>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="content">
    <?= $content ?>
</div>
<footer>
    <div class="footer-content">
        <div class="footer-content-left">Справочно-информационный ресурс POSAD-OBZOR</div>
        <div class="footer-content-right">
            <a href="http://in-quality.ru" target="_blank">
                <div class="footer-content-right-text">Сайт разработан</div>
                <div class="footer-content-right-logo"></div>
            </a>
        </div>
    </div>
</footer>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>
<?php Spaceless::end(); ?>