models/User.php
<?php

namespace app\models;

use Yii;
use yii\base\Security;
use \yii\db\ActiveRecord;
use yii\web\IdentityInterface;

/**
 * This is the model class for table "user".
 *
 * @property integer $id
 * @property string $name
 * @property string $lastname
 * @property string $patronymic
 * @property string $email
 * @property string $salt
 * @property string $password
 * @property string $main_number
 * @property string $extra_number
 * @property string $vk
 * @property string $fb
 * @property string $tw
 * @property string $mail
 * @property string $c_date
 * @property string $auth_key
 * @property string $role
 */
class User extends ActiveRecord implements IdentityInterface
{
    public $repassword;
    public $avatar;

    const RUS_NAME = false;
    const MENU_SORT = false;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['c_date', 'password', 'repassword', 'auth_key'], 'safe'],
            [['name', 'email', 'password'], 'required', 'message' => 'Поле не может быть пустым!'],
            ['repassword', 'compare', 'compareAttribute' => 'password', 'message' => 'Пароли должны совпадать!'],
            ['email', 'unique', 'targetClass' => '\app\models\User', 'message' => 'Пользователь с таким email уже существует'],
            [['name', 'lastname', 'patronymic', 'email', 'salt', 'password', 'repassword', 'main_number', 'extra_number', 'vk', 'fb', 'tw', 'mail'], 'string', 'max' => 255],
            [['avatar'], 'file', 'extensions'=> ['png', 'jpg']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'ВАШЕ ИМЯ:',
            'lastname' => 'ВАША ФАМИЛИЯ:',
            'patronymic' => 'ВАШЕ ОТЧЕСТВО:',
            'email' => 'ВАШ E-MAIL:',
            'salt' => 'Salt',
            'password' => 'ВАШ ПАРОЛЬ:',
            'repassword' => 'ПОВТОРИТЕ ПАРОЛЬ:',
            'main_number' => 'Main Number',
            'extra_number' => 'Extra Number',
            'vk' => 'Vk',
            'fb' => 'Fb',
            'tw' => 'Tw',
            'mail' => 'Mail',
            'c_date' => 'C Date',
            'auth_key' => 'C Date',
            'role' => 'Role',
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);
        // установка роли пользователя
        $auth = Yii::$app->authManager;
        $name = $this->role ? $this->role : 'user';
        $role = $auth->getRole($name);
        if (!$insert) {
            $auth->revokeAll($this->id);
        }
        $auth->assign($role, $this->id);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne($id);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        return static::findOne(['access_token' => $token]);
    }

    /**
     * Finds user by email
     *
     * @param  string      $email
     * @return static|null
     */
    public static function findByEmail($email)
    {
        return static::findOne(['email' => $email]);
    }

    /**
     * Finds user by password reset token
     *
     * @param  string      $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        $expire = \Yii::$app->params['user.passwordResetTokenExpire'];
        $parts = explode('_', $token);
        $timestamp = (int) end($parts);
        if ($timestamp + $expire < time()) {
            // token expired
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token
        ]);
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param  string  $password password to validate
     * @param  string  $db_password db password to validate
     * @param  string  $salt to password
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password, $db_password, $salt)
    {
        if (crypt($password, $salt) == $db_password) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Security::generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Security::generateRandomKey();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Security::generateRandomKey() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use app\models\ChangePasswordForm;
use Yii;
use app\models\User;
use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\filters\AccessControl;
use yii\web\Response;
use yii\widgets\ActiveForm;
use yii\web\UploadedFile;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends CController
{
    public $layout = 'lk';

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],

            'access' => [
                'class' => AccessControl::className(),
                'only' => ['create', 'update', 'edit'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => User::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $user_id
     * @return mixed
     */
    public function actionView($user_id)
    {
        return $this->render('view', [
            'model' => $this->findModel($user_id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'user_id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    public function actionEdit($user_id)
    {
        return $this->render('edit', [
            'model' => $this->findModel($user_id),
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $user_id
     * @return mixed
     */
    public function actionUpdate($user_id)
    {
        $model = $this->findModel($user_id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $this->redirect(['/user/edit', 'user_id' => \Yii::$app->user->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $user_id
     * @return mixed
     */
    public function actionDelete($user_id)
    {
        $this->findModel($user_id)->delete();

        return $this->redirect(['index']);
    }

    public function actionCp()
    {
        $model = new ChangePasswordForm();

        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }

        if ($model->load(Yii::$app->request->post())) {
            $user = User::findOne(Yii::$app->user->id);
            $user->password = crypt($model->password, $user->salt);

            if ($user->save()) {
                $this->redirect(['/user/edit', 'user_id' => Yii::$app->user->id]);
            }
        }
    }

    public function actionUploadavatar($user_id)
    {
        $model = new User();
        $model->avatar = UploadedFile::getInstance($model, 'avatar');
        if ($model->validate(['avatar'])) {
            if (!is_dir(Yii::getAlias('@webroot') . '/upload/user/'.$user_id)) {
                mkdir(Yii::getAlias('@webroot') . '/upload/user/' . $user_id);
            }
            $model->avatar->saveAs(Yii::getAlias('@webroot') . '/upload/user/' . $user_id . '/avatar.png');
            $image = Yii::$app->image->load(Yii::getAlias('@webroot') . '/upload/user/' . $user_id . '/avatar.png');
            if ($image->resize(155, false)->save()) {
                $this->redirect(['/user/edit', 'user_id' => $user_id]);
            }
        } else {
            $this->redirect(['/user/edit', 'user_id' => $user_id]);
        }
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $user_id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($user_id)
    {
        if (($model = User::findOne($user_id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'salt')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'password')->passwordInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'main_number')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'extra_number')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'vk')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'fb')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'tw')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'mail')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'c_date')->textInput() ?>

    <?= $form->field($model, 'auth_key')->textInput(['maxlength' => 255]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = 'Create User';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/user/edit.php
<?php

use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */

$this->title = 'Мой профиль / PosadObzor';
$model = \app\models\User::findOne($model->id);
$cp_form = new \app\models\ChangePasswordForm();
?>

<div class="button-edit edit_user_info button-right">Изменить</div>
<div class="content-right-title">Профиль пользователя</div>
<div class="content-right-block">
    <div class="content-right-block-user">
        <div class="content-right-block-user-left">
            <div class="content-right-block-user-left-photo">
                <?php $form = ActiveForm::begin([
                    'options' => ['enctype'=>'multipart/form-data'],
                    'action' => '/user/'.$model->id.'/uploadavatar',
                    'fieldConfig' => [
                        'template' => "{input}",
                    ],
                ]); ?>
                <?php if (file_exists(Yii::getAlias('@webroot') . '/upload/user/'.$model->id.'/avatar.png')): ?>
                    <img src="/upload/user/<?=$model->id?>/avatar.png" alt="" />
                <?php else: ?>
                    <img src="/upload/images/__blank_avatar.png" alt="" />
                <?php endif; ?>
                <?= $form->field($model, 'avatar')->fileInput(['id' => 'user-avatar', 'class' => 'image-upload']) ?>
                <label for="user-avatar" class="content-right-block-user-left-photo__upload">загрузить аватар</label>
                <?php ActiveForm::end() ?>
            </div>
        </div>
        <div class="content-right-block-user-right">
            <?php $form = ActiveForm::begin([
                'id' => 'reg-form',
                'method' => 'post',
                'action' => \yii\helpers\Url::toRoute(['/user/update', 'user_id' => \Yii::$app->user->id, '#' => 'content']),
                'options' => ['class' => 'form-horizontal'],
                'fieldConfig' => [
                    'template' => "{input}",
                ],
            ]); ?>
            <div class="content-right-block-user-right-name">
                <label for="user_name" class="content-right-block-user-right__text">
                    <?= $model->lastname . ' ' . $model->name . ' ' . $model->patronymic?>
                </label>
                <?= $form->field($model, 'lastname')->textInput([
                    'maxlength' => 255, 'class' => 'content-right-block-user-right__input', 'placeholder' => 'Фамилия'
                ]) ?>
                <?= $form->field($model, 'name')->textInput([
                    'maxlength' => 255, 'class' => 'content-right-block-user-right__input', 'placeholder' => 'Имя'
                ]) ?>
                <?= $form->field($model, 'patronymic')->textInput([
                    'maxlength' => 255, 'class' => 'content-right-block-user-right__input', 'placeholder' => 'Отчество'
                ]) ?>
            </div>
            <div class="content-right-block-user-right-phone">
                <label for="user_phone">Контактный телефон:</label>
                <div class="content-right-block-user-right__text"><?= $model->main_number ?></div>
                <?= $form->field($model, 'main_number')->textInput([
                    'maxlength' => 255, 'class' => 'content-right-block-user-right__input phone-mask'
                ]) ?>
            </div>
            <div class="content-right-block-user-right-phone">
                <label for="user_phone">Дополнительный телефон:</label>
                <div class="content-right-block-user-right__text"><?= $model->extra_number ?></div>
                <?= $form->field($model, 'extra_number')->textInput([
                    'maxlength' => 255, 'class' => 'content-right-block-user-right__input phone-mask'
                ]) ?>
            </div>
            <div class="content-right-block-user-right-email">
                <label for="user_email">Электронная почта:</label>
                <div class="content-right-block-user-right__text"><a href="mailto:<?= $model->email ?>"><?= $model->email ?></a></div>
                <?= $form->field($model, 'email')->textInput([
                    'maxlength' => 255, 'class' => 'content-right-block-user-right__input email-mask'
                ]) ?>
            </div>
            <input type="submit" class="button-save" value="Сохранить" />
            <?php ActiveForm::end(); ?>
        </div>
        <hr />
        <div class="content-right-block-user-settings">
            <div class="content-right-block-user-settings-title">Технические данные</div>
            <?php $form = ActiveForm::begin([
                'id' => 'cp-form',
                'method' => 'post',
                'action' => \yii\helpers\Url::toRoute(['/user/cp', 'user_id' => \Yii::$app->user->id, '#' => 'content']),
                'options' => ['class' => 'form-horizontal'],
                'enableAjaxValidation' => true,
                'fieldConfig' => [
                    'template' => "
                                <div class=\"content-right-block-user-settings-block\">{label}\n
                                    {input}<div class=\"field__error\">{error}</div></div>",
                ],
            ]); ?>
                <?= $form->field($cp_form, 'old_password')->passwordInput() ?>
                <?= $form->field($cp_form, 'password')->passwordInput() ?>
                <?= $form->field($cp_form, 're_password')->passwordInput() ?>
                <input type="submit" class="button-save" value="Сохранить" />
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/user/index.php
<?php

use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */

$model = \app\models\User::findOne(\Yii::$app->user->id);
?>
<div class="content-title">личный кабинет</div>
<div class="content-left">
    <div class="content-left-menu">
        <a href="<?= \yii\helpers\Url::toRoute('/user/index') ?>" class="active">Общая информация</a>
        <a href="<?= \yii\helpers\Url::toRoute('/company/index') ?>">Мои компании</a>
        <a href="<?= \yii\helpers\Url::toRoute('/goods/index') ?>">Мои товары/услуги</a>
        <a href="<?= \yii\helpers\Url::toRoute('/ad/index') ?>">Мои объявления</a>
    </div>
</div>
<div class="content-right">
    <div class="content-right-block active">
        <div class="button-edit edit_user_info">Изменить</div>
        <div class="content-right-block-title">Профиль пользователя</div>
        <div class="content-right-block-user">
            <div class="content-right-block-user-left">
                <div class="content-right-block-user-left-photo">
                    <img src="/upload/images/__blank_avatar.png" alt="" />
                    <div class="content-right-block-user-left-photo__upload">загрузить аватар</div>
                </div>
            </div>
            <div class="content-right-block-user-right">
                <?php $form = ActiveForm::begin([
                    'id' => 'reg-form',
                    'method' => 'post',
                    'action' => \yii\helpers\Url::toRoute('/user/update'),
                    'options' => ['class' => 'form-horizontal'],
                    'fieldConfig' => [
                        'template' => "{input}",
                    ],
                ]); ?>
                <div class="content-right-block-user-right-name">
                    <label for="user_name" class="content-right-block-user-right__text"><?= $model->name ?></label>
                    <?= $form->field($model, 'name')->textInput(['maxlength' => 255, 'class' => 'content-right-block-user-right__input']) ?>
                </div>
                <div class="content-right-block-user-right-phone">
                    <label for="user_phone">Контактный телефон:</label>
                    <div class="content-right-block-user-right__text"><?= $model->main_number ?></div>
                    <?= $form->field($model, 'main_number')->textInput(['maxlength' => 255, 'class' => 'content-right-block-user-right__input']) ?>
                </div>
                <div class="content-right-block-user-right-phone">
                    <label for="user_phone">Дополнительный телефон:</label>
                    <div class="content-right-block-user-right__text"><?= $model->main_number ?></div>
                    <?= $form->field($model, 'extra_number')->textInput(['maxlength' => 255, 'class' => 'content-right-block-user-right__input']) ?>
                </div>
                <div class="content-right-block-user-right-email">
                    <label for="user_email">Электронная почта:</label>
                    <div class="content-right-block-user-right__text"><a href="mailto:<?= $model->email ?>"><?= $model->email ?></a></div>
                    <?= $form->field($model, 'email')->textInput(['maxlength' => 255, 'class' => 'content-right-block-user-right__input']) ?>
                </div>
                <?php ActiveForm::end(); ?>
            </div>
            <hr />
            <div class="content-right-block-user-settings">
                <div class="content-right-block-user-settings-title">Технические данные</div>
                <form action="">
                    <div class="content-right-block-user-settings-block">
                        <label for="old_password">Старый пароль:</label>
                        <input type="password" id="old_password" />
                    </div>
                    <div class="content-right-block-user-settings-block">
                        <label for="new_password">Новый пароль:</label>
                        <input type="password" id="new_password" />
                    </div>
                    <div class="content-right-block-user-settings-block">
                        <label for="re_password">Повторите пароль:</label>
                        <input type="password" id="re_password" />
                    </div>
                    <input type="submit" class="button-edit" value="Изменить" />
                </form>
            </div>
        </div>
    </div>
    <div class="content-right-block">company</div>
    <div class="content-right-block">goods</div>
    <div class="content-right-block">ads</div>
</div>

views/user/update.php
<?php

use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */

$model = \app\models\User::findOne(\Yii::$app->user->id);
?>

<div class="button-edit edit_user_info">Изменить</div>
<div class="content-right-block-title">Профиль пользователя</div>
<div class="content-right-block-user">
    <div class="content-right-block-user-left">
        <div class="content-right-block-user-left-photo">
            <img src="/upload/images/__blank_avatar.png" alt="" />
            <div class="content-right-block-user-left-photo__upload">загрузить аватар</div>
        </div>
    </div>
    <div class="content-right-block-user-right">
        <?php $form = ActiveForm::begin([
            'id' => 'reg-form',
            'method' => 'post',
            'action' => \yii\helpers\Url::toRoute('/user/update'),
            'options' => ['class' => 'form-horizontal'],
            'fieldConfig' => [
                'template' => "{input}",
            ],
        ]); ?>
        <div class="content-right-block-user-right-name">
            <label for="user_name" class="content-right-block-user-right__text"><?= $model->name ?></label>
            <?= $form->field($model, 'name')->textInput(['maxlength' => 255, 'class' => 'content-right-block-user-right__input']) ?>
        </div>
        <div class="content-right-block-user-right-lastname">
            <label for="user_lastname" class="content-right-block-user-right__text"><?= $model->lastname ?></label>
            <?= $form->field($model, 'lastname')->textInput(['maxlength' => 255, 'class' => 'content-right-block-user-right__input']) ?>
        </div>
        <div class="content-right-block-user-right-phone">
            <label for="user_phone">Контактный телефон:</label>
            <div class="content-right-block-user-right__text"><?= $model->main_number ?></div>
            <?= $form->field($model, 'main_number')->textInput(['maxlength' => 255, 'class' => 'content-right-block-user-right__input']) ?>
        </div>
        <div class="content-right-block-user-right-phone">
            <label for="user_phone">Дополнительный телефон:</label>
            <div class="content-right-block-user-right__text"><?= $model->main_number ?></div>
            <?= $form->field($model, 'extra_number')->textInput(['maxlength' => 255, 'class' => 'content-right-block-user-right__input']) ?>
        </div>
        <div class="content-right-block-user-right-email">
            <label for="user_email">Электронная почта:</label>
            <div class="content-right-block-user-right__text"><a href="mailto:<?= $model->email ?>"><?= $model->email ?></a></div>
            <?= $form->field($model, 'email')->textInput(['maxlength' => 255, 'class' => 'content-right-block-user-right__input']) ?>
        </div>
        <input class="button-save" type="submit" value="Сохранить" />
        <?php ActiveForm::end(); ?>
    </div>
    <hr />
    <div class="content-right-block-user-settings">
        <div class="content-right-block-user-settings-title">Технические данные</div>
        <form action="">
            <div class="content-right-block-user-settings-block">
                <label for="old_password">Старый пароль:</label>
                <input type="password" id="old_password" />
            </div>
            <div class="content-right-block-user-settings-block">
                <label for="new_password">Новый пароль:</label>
                <input type="password" id="new_password" />
            </div>
            <div class="content-right-block-user-settings-block">
                <label for="re_password">Повторите пароль:</label>
                <input type="password" id="re_password" />
            </div>
            <input type="submit" class="button-edit" value="Изменить" />
        </form>
    </div>
</div>

views/user/view.php
view user public page